name: Build modified cranes
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

env:
  CRANE_DIR: "matrix-test"


# https://github.com/dorny/paths-filter#examples
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      cranes: ${{ steps.changes.outputs.changes }}
    steps:
      - name: Checkout
        id: checkout
        uses: "actions/checkout@v3"

      - id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            project1: "${{ env.CRANE_DIR }}/project1/**"
            project2: "${{ env.CRANE_DIR }}/project2/**"

  build-docker:
    name: Build crane images
    needs: changes
    strategy:
      matrix:
        crane: ${{ fromJSON(needs.changes.outputs.cranes) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Login to registry"
        id: registry-login
        uses: "docker/login-action@v2"
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout
        id: checkout
        uses: "actions/checkout@v3"

      - name: Docker meta
        id: meta
        uses: "docker/metadata-action@v4"
        with:
          images: "ghcr.io/${{ github.repository }}-${{ matrix.crane }}"
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=edge,branch=master
            type=sha
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "${{ env.CRANE_DIR }}/${{ matrix.crane }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}